# -*- coding: utf-8 -*-
"""plotly assign.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sSnZacg_574-klx4fBRw56OcItECtmD8
"""



"""Q1. Load the "titanic" dataset using the load_dataset function of seaborn. Use Plotly express to plot a
scatter plot for age and fare columns in the titanic dataset.
"""

import seaborn as sns
import plotly.express as px

titanic = sns.load_dataset("titanic")
fig = px.scatter(titanic, x="age", y="fare", color="sex")
fig.show()



"""Q2. Using the tips dataset in the Plotly library, plot a box plot using Plotly express."""

import seaborn as sns
tips= sns.load_dataset('tips')
import plotly.express as px
tips = px.data.tips()
fig = px.box(tips, x="tip")
fig.show()

tips



"""Q3. Using the tips dataset in the Plotly library, Plot a histogram for x= "sex" and y="total_bill" column in
the tips dataset. Also, use the "smoker" column with the pattern_shape parameter and the "day"
column with the color parameter.
"""

import plotly.express as px

tips = px.data.tips()
fig = px.histogram(tips, x="sex", y="total_bill", color="day", pattern_shape="smoker")
fig.show()



"""Q4. Using the iris dataset in the Plotly library, Plot a scatter matrix plot, using the "species" column for
the color parameter.

"""

import plotly.express as px
iris = px.data.iris()
fig = px.scatter_matrix(iris, dimensions=["sepal_length", "sepal_width", "petal_length", "petal_width"], color="species")
fig.show()



"""Q5. What is Distplot? Using Plotly express, plot a distplot.


answer:-A distplot is a statistical plot that shows the distribution of a dataset. It is a combination of a histogram and a kernel density estimate (KDE). The histogram shows the frequency of each value in the dataset, and the KDE shows the smooth distribution of the data.
The distplot will show the distribution of the height data in the iris dataset. The histogram will show the frequency of each height value, and the KDE will show the smooth distribution of the data.
"""

